function [DE_target, R_total, passivity_error] = RCWA_Engine_Config(period_um, theta_B_deg, wavelengths_nm, theta_inc_deg, order, N_layers, target_harmonic, material_csv)
% Parameterized TE-polarized reflective RCWA solver with an opaque Al substrate.
% Optical constants are read from the source-attributed Rakić 1998
% Brendel-Bormann material table generated by the paper workflow.

if nargin < 5, order = 11; end
if nargin < 6, N_layers = 31; end
if nargin < 7, target_harmonic = 1; end  % Historical mapping to optical -1 order.
if nargin < 8 || isempty(material_csv)
    workflow_dir = fileparts(fileparts(mfilename('fullpath')));
    material_csv = fullfile(workflow_dir,'materials','Al_Rakic_BB_400_1700nm.csv');
end
if ~exist(material_csv,'file')
    error('Al material table not found: %s',material_csv);
end

num_points = length(wavelengths_nm);
DE_target = zeros(1, num_points);
R_total = zeros(1, num_points);
passivity_error = zeros(1, num_points);

theta_inc = theta_inc_deg * pi / 180;

theta_B = theta_B_deg * pi / 180;
H = period_um * sin(theta_B) * cos(theta_B);

i = -order:order;
N_harmonics = length(i);
center_idx = order + 1;
target_idx = find(i == target_harmonic, 1);
if isempty(target_idx)
    error('target_harmonic is outside the retained Fourier orders');
end
dz = H / N_layers;
e_inc = 1.0;
ngr = 1.0;
h_vals = -2*order:2*order;

for wl_idx = 1:num_points
    lambda_nm = wavelengths_nm(wl_idx);
    lambda_um = lambda_nm / 1000;
    k0 = 2*pi/lambda_um;
    n_Al = get_Al_index_local(lambda_nm,material_csv);
    e_sub = n_Al^2;

    kxi = k0 .* (sqrt(e_inc) .* sin(theta_inc) - i .* (lambda_um / period_um));
    kz1 = conj(sqrt(e_inc .* k0.^2 - kxi.^2 + 1e-10i));
    kz2 = conj(sqrt(e_sub .* k0.^2 - kxi.^2 + 1e-10i));
    Y1 = diag(kz1 ./ k0);
    Y2 = diag(kz2 ./ k0);
    Kx = diag(kxi ./ k0);

    S_global.S11 = zeros(N_harmonics);
    S_global.S12 = eye(N_harmonics);
    S_global.S21 = eye(N_harmonics);
    S_global.S22 = zeros(N_harmonics);
    W_prev = eye(N_harmonics);
    V_prev = 1i * Y1;
    e_grating = zeros(1, length(h_vals));

    for layer_idx = 1:N_layers
        h_center = H - (layer_idx - 0.5) * dz;
        xL = h_center * cot(theta_B);
        xR = period_um - h_center * tan(theta_B);
        for h_idx = 1:length(h_vals)
            h_order = h_vals(h_idx);
            if h_order == 0
                fill = (xR - xL) / period_um;
                e_grating(h_idx) = n_Al^2 * fill + ngr^2 * (1-fill);
            else
                term1 = exp(-1i * 2*pi*h_order*xR/period_um);
                term2 = exp(-1i * 2*pi*h_order*xL/period_um);
                e_grating(h_idx) = (n_Al^2-ngr^2)/(-1i*2*pi*h_order) * (term1-term2);
            end
        end
        E = zeros(N_harmonics);
        for s = 1:N_harmonics
            for p = 1:N_harmonics
                h_diff = i(s)-i(p);
                E(s,p) = e_grating(h_vals == h_diff);
            end
        end
        [W, Q_sq] = eig(Kx.^2-E);
        Qm = sqrt(Q_sq);
        V = W*Qm;
        X = diag(exp(-k0*diag(Qm)*dz));
        A_int = 0.5*(W_prev\W + V_prev\V);
        B_int = 0.5*(W_prev\W - V_prev\V);
        S_int.S11 = B_int/A_int;
        S_int.S12 = A_int-B_int*(A_int\B_int);
        S_int.S21 = inv(A_int);
        S_int.S22 = -A_int\B_int;
        S_prop.S11 = zeros(N_harmonics);
        S_prop.S12 = X;
        S_prop.S21 = X;
        S_prop.S22 = zeros(N_harmonics);
        S_global = star_product_local(S_global,S_int,N_harmonics);
        S_global = star_product_local(S_global,S_prop,N_harmonics);
        W_prev = W;
        V_prev = V;
    end

    A_int = 0.5*(W_prev\eye(N_harmonics) + V_prev\(1i*Y2));
    B_int = 0.5*(W_prev\eye(N_harmonics) - V_prev\(1i*Y2));
    S_int.S11 = B_int/A_int;
    S_int.S12 = A_int-B_int*(A_int\B_int);
    S_int.S21 = inv(A_int);
    S_int.S22 = -A_int\B_int;
    S_global = star_product_local(S_global,S_int,N_harmonics);

    delta = zeros(N_harmonics,1);
    delta(center_idx) = 1;
    Er = S_global.S11*delta;
    inc_poynting = real(kz1(center_idx)/k0);
    series_R = real(kz1')/k0;
    DEr_all = abs(Er).^2 .* series_R / inc_poynting;
    DEr_all(~isfinite(DEr_all)) = 0;
    DEr_all = max(real(DEr_all),0);
    DE_target(wl_idx) = DEr_all(target_idx);
    R_total(wl_idx) = sum(DEr_all);
    passivity_error(wl_idx) = max(R_total(wl_idx)-1,0);
end
end


function S = star_product_local(Sa,Sb,N)
I = eye(N);
inv_term1 = (I-Sa.S22*Sb.S11)\I;
inv_term2 = (I-Sb.S11*Sa.S22)\I;
S.S11 = Sa.S11+Sa.S12*Sb.S11*inv_term1*Sa.S21;
S.S12 = Sa.S12*inv_term2*Sb.S12;
S.S21 = Sb.S21*inv_term1*Sa.S21;
S.S22 = Sb.S22+Sb.S21*Sa.S22*inv_term2*Sb.S12;
end


function n_Al = get_Al_index_local(lambda_nm,material_csv)
persistent cached_path wl_data n_data k_data
if isempty(cached_path) || ~strcmp(cached_path,material_csv)
    material = readtable(material_csv);
    required = {'wavelength_nm','n','k'};
    if ~all(ismember(required,material.Properties.VariableNames))
        error('Material CSV must contain wavelength_nm, n, and k columns');
    end
    wl_data = material.wavelength_nm(:)';
    n_data = material.n(:)';
    k_data = material.k(:)';
    cached_path = material_csv;
end
if lambda_nm < min(wl_data) || lambda_nm > max(wl_data)
    error('Requested wavelength %.6g nm is outside material-table range',lambda_nm);
end
nR = interp1(wl_data,n_data,lambda_nm,'linear','extrap');
nI = interp1(wl_data,k_data,lambda_nm,'linear','extrap');
n_Al = nR-1i*nI;
end
